#!/bin/sh
echo "Executing $0 : $@"
echo "Bringing down $1 for bridged mode..."
sudo /sbin/ifconfig $1 0.0.0.0 promisc down
echo "Deleting $1 to br0..."
sudo /usr/sbin/brctl delif br0 $1
echo "$0 : END"
